name: hello-snap
version: '0.1'
summary: A simple "Hello, Snap!" program
description: |
  A simple "Hello, Snap!" program in C++

architectures:
  - build-on: amd64
    build-for: amd64
  - build-on: [amd64, arm64]
    build-for: arm64

confinement: strict

base: core22
grade: devel

apps:
  hello-snap:
    command: hello-snap
    plugs: [home]

parts:
  local:
    plugin: make
    source: .